#!/usr/bin/bash

python3 main_test_script.py --filepath "videos/stfp_CNL/NPD 541 CHSW 2019 June 14.mp4" && python3 main_test_script.py --filepath "videos/stfp_CNL/NPD 541 CHSW 2019 June 14.mp4" --classify
